[project]
name = "hello-waveshare-epaper-display"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gpiozero>=2.0.1",
    "pillow>=11.3.0",
    "qrcode[pil]>=8.2",
    "rpi-lgpio>=0.6",
    "spidev>=3.8",
]
